#############################################################################
# Makefile for building: qml_location_mapviewer.app/Contents/MacOS/qml_location_mapviewer
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ../mapviewer/mapviewer.pro
# Template: app
# Command: /Users/usmarpadow/Qt/5.7/ios/bin/qmake -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug -spec macx-xcode -o qml_location_mapviewer.xcodeproj/project.pbxproj ../mapviewer/mapviewer.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/usmarpadow/Qt/5.7/ios/bin/qmake
qml_location_mapviewer.xcodeproj/project.pbxproj: ../mapviewer/mapviewer.pro /Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/qmake.conf /Users/usmarpadow/Qt/5.7/ios/mkspecs/features/spec_pre.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/qdevice.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/device_config.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/unix.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/mac.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/sanitize.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/gcc-base.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/clang.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/clang-mac.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios/clang.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios/qmake.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/qconfig.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_dbus.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_script.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_iosgamepad.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qdds.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt_functions.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt_config.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/exclusive_builds.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/default_pre.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/default_pre.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/resolve_config.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/resolve_config.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/default_post.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/sdk.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/sdk.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/default_post.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/objective_c.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qml_debug.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/warn_on.prf \
		/Users/usmarpadow/Qt/5.7/ios/plugins/platforms/libqios_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/qt.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/resources.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/moc.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/unix/opengl.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/unix/thread.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/file_copies.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/rez.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/testcase_targets.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/exceptions.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/yacc.prf \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/lex.prf \
		../mapviewer/mapviewer.pro \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../mapviewer/mapviewer.qrc \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5DBus_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libqtfreetype_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Gui_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Core_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libqtpcre_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Location_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Quick_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Qml_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Network_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Positioning_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick.2/libqtquick2plugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtLocation/libdeclarative_location_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtPositioning/libdeclarative_positioning_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Window.2/libwindowplugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_mapbox_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_nokia_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_osm_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqmacjp2_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqwebp_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_debugger_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_inspector_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_local_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_native_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_profiler_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_quickprofiler_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_server_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_tcp_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/bearer/libqgenericbearer_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_cl_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_geoclue_iphonesimulator_debug.prl \
		/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_positionpoll_iphonesimulator_debug.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug -spec macx-xcode -o qml_location_mapviewer.xcodeproj/project.pbxproj ../mapviewer/mapviewer.pro
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/spec_pre.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/qdevice.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/device_config.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/unix.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/mac.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/sanitize.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/gcc-base.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/gcc-base-mac.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/clang.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/clang-mac.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios/clang.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/common/ios/qmake.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/qconfig.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dextras.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_core.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_dbus.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gamepad.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_help.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_location.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_network.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_purchasing.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_script.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_script_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scripttools.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scxml.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_iosgamepad.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qdds.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt_functions.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt_config.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-xcode/qmake.conf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/exclusive_builds.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/default_pre.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/default_pre.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/resolve_config.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/resolve_config.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/default_post.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/sdk.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/sdk.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/default_post.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/objective_c.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qml_debug.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/warn_on.prf:
/Users/usmarpadow/Qt/5.7/ios/plugins/platforms/libqios_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/qt.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/qt.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/resources.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/moc.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/unix/opengl.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/unix/thread.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/file_copies.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/mac/rez.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/testcase_targets.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/exceptions.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/yacc.prf:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/features/lex.prf:
../mapviewer/mapviewer.pro:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/usmarpadow/Qt/5.7/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../mapviewer/mapviewer.qrc:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5DBus_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libqtfreetype_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Gui_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Core_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libqtpcre_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Location_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Quick_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Qml_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Network_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/lib/libQt5Positioning_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick.2/libqtquick2plugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtLocation/libdeclarative_location_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtPositioning/libdeclarative_positioning_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Window.2/libwindowplugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_mapbox_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_nokia_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/geoservices/libqtgeoservices_osm_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqmacjp2_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/imageformats/libqwebp_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_debugger_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_inspector_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_local_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_native_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_profiler_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_quickprofiler_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_server_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/qmltooling/libqmldbg_tcp_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/bearer/libqgenericbearer_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_cl_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_geoclue_iphonesimulator_debug.prl:
/Users/usmarpadow/Qt/5.7/ios/plugins/position/libqtposition_positionpoll_iphonesimulator_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug -spec macx-xcode -o qml_location_mapviewer.xcodeproj/project.pbxproj ../mapviewer/mapviewer.pro

qmake_all: FORCE

